import type { Country, SovereigntyType } from "../../features/countries";

export const mockCountries: Country[] = [
  {
    name: "France",
    isoCode: "FR",
    region: "Europe",
    subregion: "Western Europe",
    sovereigntyType: "Sovereign" as SovereigntyType,
    callingCode: "+33",
    iso3Code: "FRA",
    currency: "EUR",
    languages: ["French"],
    capital: "Paris",
    population: 50000000,
  },
  {
    name: "Guadeloupe",
    isoCode: "GP",
    region: "Americas",
    subregion: "Caribbean",
    sovereigntyType: "Dependency" as SovereigntyType,
    callingCode: "+590",
    iso3Code: "GLP",
    currency: "EUR",
    languages: ["French"],
    population: 1800,
  },
  {
    name: "Germany",
    isoCode: "DE",
    region: "Europe",
    subregion: "Western Europe",
    sovereigntyType: "Sovereign" as SovereigntyType,
    callingCode: "+49",
    iso3Code: "DEU",
    currency: "EUR",
    languages: ["German"],
    population: 8300,
  },
  {
    name: "Canada",
    isoCode: "CA",
    region: "Americas",
    subregion: "Northern America",
    sovereigntyType: "Sovereign" as SovereigntyType,
    callingCode: "+1",
    iso3Code: "CAN",
    population: 3800,
  },
  {
    name: "United States",
    isoCode: "US",
    region: "Americas",
    subregion: "Northern America",
    sovereigntyType: "Sovereign" as SovereigntyType,
    callingCode: "+1",
    iso3Code: "USA",
    population: 3300,
  },
  {
    name: "Japan",
    isoCode: "JP",
    region: "Asia",
    subregion: "Eastern Asia",
    sovereigntyType: "Sovereign" as SovereigntyType,
    callingCode: "+81",
    iso3Code: "JPN",
    population: 12600,
  },
];
