import { vi } from "vitest";
import type { UIContextType } from "@contexts/UIContext";

export const mockUIContext: UIContextType = {
  uiVisible: true,
  setUiVisible: vi.fn(),
  toggleUiVisible: vi.fn(),
  sidebarExpanded: false,
  setSidebarExpanded: vi.fn(),
  openMapToolbarPanel: null,
  showCountries: false,
  toggleCountries: vi.fn(),
  showFilters: false,
  toggleFilters: vi.fn(),
  showLayers: false,
  toggleLayers: vi.fn(),
  showMarkers: false,
  toggleMarkers: vi.fn(),
  showSavedMaps: false,
  toggleSavedMaps: vi.fn(),
  showExport: false,
  toggleExport: vi.fn(),
  showSettings: false,
  toggleSettings: vi.fn(),
  openUserPanel: null,
  showFriends: false,
  toggleFriends: vi.fn(),
  showSearch: false,
  toggleSearch: vi.fn(),
  showHelp: false,
  toggleHelp: vi.fn(),
  closePanel: vi.fn(),
  modalOpen: false,
  setModalOpen: vi.fn(),
  showLegend: false,
  toggleLegend: vi.fn(),
  closeLegend: vi.fn(),
  showShortcuts: false,
  toggleShortcuts: vi.fn(),
  closeShortcuts: vi.fn(),
  showCalendar: false,
  calendarDate: undefined,
  handleViewInCalendar: vi.fn(),
  toggleCalendar: vi.fn(),
  closeCalendar: vi.fn(),  
};
