import type { UIContextType } from "@contexts/UIContext";
import { vi } from "vitest";

export const mockUIContext: UIContextType = {
  uiVisible: true,
  setUiVisible: vi.fn(),
  sidebarExpanded: false,
  setSidebarExpanded: vi.fn(),
  showCountries: false,
  toggleCountries: vi.fn(),
  showFilters: false,
  toggleFilters: vi.fn(),
  showMarkers: false,
  toggleMarkers: vi.fn(),
  showOverlays: false,
  toggleOverlays: vi.fn(),
  showExport: false,
  toggleExport: vi.fn(),
  showSettings: false,
  toggleSettings: vi.fn(),
  closePanel: vi.fn(),
  modalOpen: false,
  setModalOpen: vi.fn(),
  showLegend: false,
  toggleLegend: vi.fn(),
  closeLegend: vi.fn(),
  showShortcuts: false,
  toggleShortcuts: vi.fn(),
  closeShortcuts: vi.fn(),
};
