import type { Country, SovereigntyStatus } from "../../features/countries/types";

export const mockCountries: Country[] = [
  {
    name: "France",
    isoCode: "FR",
    iso3Code: "FRA",
    region: "Europe",
    subregion: "Western Europe",
    capital: "Paris",
    languages: ["French"],
    area: 551695,
    population: 50000000,
    currency: "EUR",
    timezones: ["Europe/Paris"],
    callingCode: "+33",
    sovereigntyStatus: "sovereign" as SovereigntyStatus,
    geoType: "Coastal",
    unMember: true,
    territories: {
      dependencies: { codes: ["CP"] },
      overseas_regions: { codes: ["GP"] },
      disputes: { codes: ["US"] },
    },
  },
  {
    name: "Guadeloupe",
    isoCode: "GP",
    iso3Code: "GLP",
    region: "Americas",
    subregion: "Caribbean",
    languages: ["French"],
    area: 1628,
    population: 1800,
    currency: "EUR",
    timezones: ["America/Guadeloupe"],
    callingCode: "+590",
    sovereigntyStatus: "dependency" as SovereigntyStatus,
    sovereignState: "FR",
    geoType: "Island",
    unMember: false,
  },
  {
    name: "Germany",
    isoCode: "DE",
    iso3Code: "DEU",
    region: "Europe",
    subregion: "Western Europe",
    languages: ["German"],
    area: 357022,
    population: 8300,
    currency: "EUR",
    timezones: ["Europe/Berlin"],
    callingCode: "+49",
    sovereigntyStatus: "sovereign" as SovereigntyStatus,
    geoType: "Landlocked",
    unMember: true,
  },
  {
    name: "Canada",
    isoCode: "CA",
    iso3Code: "CAN",
    region: "Americas",
    subregion: "Northern America",
    area: 9984670,
    population: 3800,
    timezones: ["America/Toronto"],
    callingCode: "+1",
    sovereigntyStatus: "sovereign" as SovereigntyStatus,
    geoType: "Coastal",
    unMember: true,
  },
  {
    name: "United States",
    isoCode: "US",
    iso3Code: "USA",
    region: "Americas",
    subregion: "Northern America",
    transcontinental: {
      additionalRegion: "Oceania",
      additionalSubregion: "Polynesia",
      scope: "overseas",
    },
    area: 9833520,
    population: 3300,
    timezones: ["America/New_York"],
    callingCode: "+1",
    sovereigntyStatus: "sovereign" as SovereigntyStatus,
    geoType: "Coastal",
    altNames: ["USA", "US", "United States of America"],
    unMember: true,
    territories: {
      dependencies: { codes: ["GU"], label: "Dependency" },
      disputes: { codes: ["FR"] },
    },
  },
  {
    name: "Japan",
    isoCode: "JP",
    iso3Code: "JPN",
    region: "Asia",
    subregion: "Eastern Asia",
    area: 377975,
    population: 12600,
    timezones: ["Asia/Tokyo"],
    callingCode: "+81",
    sovereigntyStatus: "sovereign" as SovereigntyStatus,
    geoType: "Island",
    unMember: true,
  },
];
