import type { IconType } from "react-icons";
import {
  FaBagShopping,
  FaBolt,
  FaBriefcase,
  FaBuilding,
  FaCar,
  FaFutbol,
  FaGem,
  FaGraduationCap,
  FaHandshakeAngle,
  FaHandsPraying,
  FaHeart,
  FaLandmark,
  FaLocationDot,
  FaMasksTheater,
  FaMusic,
  FaPaw,
  FaPersonHiking,
  FaPersonSkiing,
  FaPersonSnowboarding,
  FaPeopleGroup,
  FaQuestion,
  FaRing,
  FaShip,
  FaSpa,
  FaTree,
  FaUmbrellaBeach,
  FaUser,
  FaUsers,
  FaUtensils,
  FaClipboard,
} from "react-icons/fa6";
import { MdBackpack } from "react-icons/md";

export const ALL_TRIP_CATEGORIES = [
  "solo",
  "couple",
  "family",
  "group",
  "organized",
  "business",
  "educational",
  "volunteering",
  "religious",
  "adventure",
  "nature",
  "backpacking",
  "roadtrip",
  "cruise",
  "luxury",
  "honeymoon",
  "wellness",
  "local",
  "food",
  "festival",
  "sports",
  "shopping",
  "beach",
  "skiing",
  "snowboarding",
  "extreme",
  "wildlife",
  "historical",
  "architectural",
  "cultural",
  "other",
] as const;

export const TRIP_CATEGORY_ICONS: Record<string, IconType> = {
  solo: FaUser,
  couple: FaHeart,
  family: FaUsers,
  group: FaPeopleGroup,
  organized: FaClipboard,
  business: FaBriefcase,
  educational: FaGraduationCap,
  volunteering: FaHandshakeAngle,
  religious: FaHandsPraying,
  adventure: FaPersonHiking,
  nature: FaTree,
  backpacking: MdBackpack,
  roadtrip: FaCar,
  cruise: FaShip,
  luxury: FaGem,
  honeymoon: FaRing,
  wellness: FaSpa,
  local: FaLocationDot,
  food: FaUtensils,
  festival: FaMusic,
  sports: FaFutbol,
  shopping: FaBagShopping,
  beach: FaUmbrellaBeach,
  skiing: FaPersonSkiing,
  snowboarding: FaPersonSnowboarding,
  extreme: FaBolt,
  wildlife: FaPaw,
  historical: FaLandmark,
  architectural: FaBuilding,
  cultural: FaMasksTheater,
  other: FaQuestion,
};
