import {
  FaArrowLeft,
  FaArrowRight,
  FaArrowsRotate,
  FaBell,
  FaBinoculars,
  FaBookAtlas,
  FaBookmark,
  FaBug,
  FaCalendar,
  FaCalendarDay,
  FaChartSimple,
  FaCheck,
  FaCircleInfo,
  FaCircleQuestion,
  FaCircleUser,
  FaClipboardList,
  FaCode,
  FaCompass,
  FaCompassDrafting,
  FaCopy,
  FaCrosshairs,
  FaDatabase,
  FaDownload,
  FaEarthAmericas,
  FaFileExport,
  FaFileImport,
  FaFilter,
  FaFlag,
  FaFloppyDisk,
  FaGear,
  FaGlobe,
  FaHatWizard,
  FaHouse,
  FaKeyboard,
  FaLandmark,
  FaLaptopCode,
  FaLayerGroup,
  FaLeaf,
  FaLink,
  FaListUl,
  FaLocationDot,
  FaMap,
  FaMapLocationDot,
  FaMapPin,
  FaMedal,
  FaPencil,
  FaPenToSquare,
  FaPercent,
  FaPlane,
  FaPlus,
  FaQuestion,
  FaRegClock,
  FaRegEye,
  FaRightFromBracket,
  FaRocket,
  FaRotateLeft,
  FaShareFromSquare,
  FaShareNodes,
  FaSuitcaseRolling,
  FaTimeline,
  FaTrash,
  FaTrophy,
  FaUniversalAccess,
  FaUser,
  FaUserGear,
  FaUserGroup,
  FaUserPlus,
  FaXmark,
} from "react-icons/fa6";
import { DashboardIcon } from "../components/icons/DashboardIcon";
import { VisitIcon } from "../components/icons/VisitIcon";

// Centralized icon mapping for shared concepts
export const ICONS = {
  // User
  account: FaCircleUser,
  profile: FaUser,  
  location: FaLocationDot,
  friends: FaUserGroup,
  friendRequests: FaUserPlus,
  settings: FaGear,
  activity: FaRegClock,
  signOut: FaRightFromBracket,
  // Atlas
  atlas: FaEarthAmericas,
  map: FaMap,
  mapData: FaMapLocationDot,
  countries: FaGlobe,
  visits: VisitIcon,
  filters: FaFilter,
  layers: FaLayerGroup,
  markers: FaMapPin,
  legend: FaListUl,
  saved: FaBookmark,
  timeline: FaTimeline,
  export: FaShareFromSquare,
  share: FaShareNodes,
  mapSettings: FaGear,
  mapConfig: FaCompassDrafting,
  // Trips
  trips: FaSuitcaseRolling,
  tripLocal: FaLocationDot,
  tripAbroad: FaPlane,
  tripPlanned: FaClipboardList,
  tripUpcoming: FaCalendarDay,
  tripCompleted: FaCheck,
  tripFilters: FaPercent,
  // Dashboard
  dashboard: DashboardIcon,
  overview: FaHouse,
  exploration: FaBookAtlas,
  achievements: FaMedal,
  statistics: FaChartSimple,
  // Quizzes
  quizzes: FaQuestion,
  quizFlag: FaFlag,
  quizCapital: FaLandmark,
  quizEasy: FaLeaf,
  quizMedium: FaCompass,
  quizHard: FaBinoculars,
  quizExpert: FaHatWizard,
  leaderboards: FaTrophy,
  // Misc
  shortcuts: FaKeyboard,
  calendar: FaCalendar,
  notifications: FaBell,
  help: FaCircleQuestion,
  info: FaCircleInfo,
  reportBug: FaBug,
  // Actions
  add: FaPlus,
  importFile: FaFileImport,
  exportFile: FaFileExport,
  view: FaRegEye,
  download: FaDownload,
  edit: FaPenToSquare,
  save: FaFloppyDisk,
  rename: FaPencil,
  center: FaCrosshairs,
  duplicate: FaCopy,
  shareWith: FaUserPlus,
  copyLink: FaLink,
  remove: FaTrash,
  reset: FaRotateLeft,
  refresh: FaArrowsRotate,
  forward: FaArrowRight,
  back: FaArrowLeft,
  close: FaXmark,
  // Docs
  gettingStarted: FaRocket,
  usingAtlaset: FaCompass,
  accountManagement: FaUserGear,
  accessibility: FaUniversalAccess,
  developers: FaCode,
  laptopCode: FaLaptopCode,
  data: FaDatabase,
};
