import {
  FaArrowLeft,
  FaArrowRight,
  FaBell,
  FaBookAtlas,
  FaBookmark,
  FaBug,
  FaCalendar,
  FaCalendarDays,
  FaChartSimple,
  FaCheck,
  FaCircleQuestion,
  FaCircleUser,
  FaClipboard,
  FaCode,
  FaCompass,
  FaCompassDrafting,
  FaDatabase,
  FaDownload,
  FaEarthAmericas,
  FaFilter,
  FaGear,
  FaGlobe,
  FaHouse,
  FaKeyboard,
  FaLaptopCode,
  FaLayerGroup,
  FaListUl,
  FaLocationDot,
  FaMap,
  FaMapLocationDot,
  FaMapPin,
  FaMedal,
  FaPercent,
  FaPlane,
  FaQuestion,
  FaRegClock,
  FaRightFromBracket,
  FaRocket,
  FaShareFromSquare,
  FaSuitcaseRolling,
  FaTimeline,
  FaTrophy,
  FaUniversalAccess,
  FaUser,
  FaUserGear,
  FaUserGroup,
} from "react-icons/fa6";
import { DashboardIcon } from "../components/icons/DashboardIcon";

// Centralized icon mapping for shared concepts
export const ICONS = {
  // User
  account: FaCircleUser,
  profile: FaUser,
  friends: FaUserGroup,
  settings: FaGear,
  activity: FaRegClock,
  signOut: FaRightFromBracket,
  // Atlas
  atlas: FaEarthAmericas,
  map: FaMap,
  mapData: FaMapLocationDot,
  countries: FaGlobe,
  filters: FaFilter,
  layers: FaLayerGroup,
  markers: FaMapPin,
  legend: FaListUl,
  saved: FaBookmark,
  timeline: FaTimeline,
  export: FaShareFromSquare,
  mapSettings: FaGear,
  mapConfig: FaCompassDrafting,
  // Trips
  trips: FaSuitcaseRolling,
  tripLocal: FaLocationDot,
  tripAbroad: FaPlane,
  tripPlanned: FaClipboard,
  tripUpcoming: FaCalendarDays,
  tripCompleted: FaCheck,
  tripFilters: FaPercent,
  // Dashboard
  dashboard: DashboardIcon,
  overview: FaHouse,
  exploration: FaBookAtlas,
  achievements: FaMedal,
  statistics: FaChartSimple,
  // Quizzes
  quizzes: FaQuestion,
  leaderboards: FaTrophy,
  // Misc
  shortcuts: FaKeyboard,
  calendar: FaCalendar,
  notifications: FaBell,
  help: FaCircleQuestion,
  reportBug: FaBug,
  // Actions
  download: FaDownload,
  navigate: FaArrowRight,
  exit: FaArrowLeft,  
  // Docs
  gettingStarted: FaRocket,
  usingAtlaset: FaCompass,
  accountManagement: FaUserGear,
  accessibility: FaUniversalAccess,
  developers: FaCode,
  laptopCode: FaLaptopCode,
  data: FaDatabase,
};
