export const categoryColumns = [
  ["General", "User"],
  ["Atlas"],
  ["Countries"],
  ["Map", "Timeline"],
];

export const keyCommands = [
  // General
  {
    id: "shortcuts.show",
    key: "?",
    modifiers: ["Shift"],
    category: "General",
    labelKey: "shortcuts.actions.general.show",
  },
  {
    id: "search.focus",
    key: "/",
    modifiers: [],
    category: "General",
    labelKey: "shortcuts.actions.general.search",
  },
  {
    id: "ui.unfocus",
    key: "Esc",
    modifiers: [],
    category: "General",
    labelKey: "shortcuts.actions.general.unfocus",
  },
  {
    id: "help.toggle",
    key: "h",
    modifiers: [],
    category: "General",
    labelKey: "shortcuts.actions.general.help",
  },
  {
    id: "filters.reset",
    key: "r",
    modifiers: [],
    category: "General",
    labelKey: "shortcuts.actions.general.resetFilters",
  },

  // User
  {
    id: "friends.toggle",
    key: "n",
    modifiers: [],
    category: "User",
    labelKey: "shortcuts.actions.user.friends",
  },

  // Atlas
  {
    id: "atlas.savedMaps",
    key: "b",
    modifiers: [],
    category: "Atlas",
    labelKey: "shortcuts.actions.atlas.savedMaps",
  },
  {
    id: "atlas.countries",
    key: "c",
    modifiers: [],
    category: "Atlas",
    labelKey: "shortcuts.actions.atlas.countries",
  },
  {
    id: "atlas.export",
    key: "e",
    modifiers: [],
    category: "Atlas",
    labelKey: "shortcuts.actions.atlas.export",
  },
  {
    id: "atlas.filters",
    key: "f",
    modifiers: [],
    category: "Atlas",
    labelKey: "shortcuts.actions.atlas.filters",
  },
  {
    id: "atlas.legend",
    key: "g",
    modifiers: [],
    category: "Atlas",
    labelKey: "shortcuts.actions.atlas.legend",
  },
  {
    id: "atlas.layers",
    key: "l",
    modifiers: [],
    category: "Atlas",
    labelKey: "shortcuts.actions.atlas.layers",
  },
  {
    id: "atlas.markers",
    key: "m",
    modifiers: [],
    category: "Atlas",
    labelKey: "shortcuts.actions.atlas.markers",
  },
  {
    id: "atlas.atlasMode",
    key: "a",
    modifiers: [],
    category: "Atlas",
    labelKey: "shortcuts.actions.atlas.atlasMode",
  },
  {
    id: "atlas.settings",
    key: "s",
    modifiers: [],
    category: "Atlas",
    labelKey: "shortcuts.actions.atlas.settings",
  },
  {
    id: "atlas.timeline",
    key: "t",
    modifiers: [],
    category: "Atlas",
    labelKey: "shortcuts.actions.atlas.timeline",
  },
  {
    id: "atlas.ui",
    key: "u",
    modifiers: [],
    category: "Atlas",
    labelKey: "shortcuts.actions.atlas.ui",
  },

  // Countries
  {
    id: "countries.scrollUp",
    key: "ArrowUp",
    modifiers: [],
    category: "Countries",
    labelKey: "shortcuts.actions.countries.scrollUp",
  },
  {
    id: "countries.scrollDown",
    key: "ArrowDown",
    modifiers: [],
    category: "Countries",
    labelKey: "shortcuts.actions.countries.scrollDown",
  },
  {
    id: "countries.first",
    key: "Home",
    modifiers: [],
    category: "Countries",
    labelKey: "shortcuts.actions.countries.first",
  },
  {
    id: "countries.last",
    key: "End",
    modifiers: [],
    category: "Countries",
    labelKey: "shortcuts.actions.countries.last",
  },
  {
    id: "countries.pageUp",
    key: "PgUp",
    modifiers: [],
    category: "Countries",
    labelKey: "shortcuts.actions.countries.pageUp",
  },
  {
    id: "countries.pageDown",
    key: "PgDn",
    modifiers: [],
    category: "Countries",
    labelKey: "shortcuts.actions.countries.pageDown",
  },
  {
    id: "countries.select",
    key: "Enter",
    modifiers: [],
    category: "Countries",
    labelKey: "shortcuts.actions.countries.select",
  },

  // Map
  {
    id: "map.zoomIn",
    key: "+",
    modifiers: [],
    category: "Map",
    labelKey: "shortcuts.actions.map.zoomIn",
  },
  {
    id: "map.zoomOut",
    key: "-",
    modifiers: [],
    category: "Map",
    labelKey: "shortcuts.actions.map.zoomOut",
  },
  {
    id: "map.zoomReset",
    key: "0",
    modifiers: [],
    category: "Map",
    labelKey: "shortcuts.actions.map.zoomReset",
  },
  {
    id: "map.center",
    key: "x",
    modifiers: [],
    category: "Map",
    labelKey: "shortcuts.actions.map.center",
  },

  // Timeline
  {
    id: "timeline.next",
    key: "ArrowRight",
    modifiers: [],
    category: "Timeline",
    labelKey: "shortcuts.actions.timeline.next",
  },
  {
    id: "timeline.prev",
    key: "ArrowLeft",
    modifiers: [],
    category: "Timeline",
    labelKey: "shortcuts.actions.timeline.prev",
  },
  {
    id: "timeline.first",
    key: "Home",
    modifiers: [],
    category: "Timeline",
    labelKey: "shortcuts.actions.timeline.first",
  },
  {
    id: "timeline.last",
    key: "End",
    modifiers: [],
    category: "Timeline",
    labelKey: "shortcuts.actions.timeline.last",
  },
  {
    id: "timeline.playPause",
    key: "Space",
    modifiers: [],
    category: "Timeline",
    labelKey: "shortcuts.actions.timeline.playPause",
  },
] as const;
