export const RATING_OPTIONS = [
  { value: -1, label: "All ratings" },
  { value: 5, label: "5 stars" },
  { value: 4.5, label: "4.5 stars" },
  { value: 4, label: "4 stars" },
  { value: 3.5, label: "3.5 stars" },
  { value: 3, label: "3 stars" },
  { value: 2.5, label: "2.5 stars" },
  { value: 2, label: "2 stars" },
  { value: 1.5, label: "1.5 stars" },
  { value: 1, label: "1 star" },
  { value: 0.5, label: "0.5 stars" },
  { value: 0, label: "No rating" },
];

export const ALL_TRIP_CATEGORIES = [
  "solo",
  "couple",
  "family",
  "group",
  "organized",
  "business",
  "educational",
  "volunteering",
  "religious",
  "adventure",
  "nature",
  "backpacking",
  "roadtrip",
  "cruise",
  "luxury",
  "honeymoon",
  "wellness",
  "local",
  "food",
  "festival",
  "sports",
  "shopping",
  "beach",
  "skiing",
  "snowboarding",
  "extreme",
  "wildlife",
  "historical",
  "architectural",
  "cultural",
  "other",
] as const;

export const ALL_TRIP_STATUSES = [
  "planned",
  "in-progress",
  "completed",
  "cancelled",
] as const;

export const ALL_TRIP_TAGS = [
  "beach",
  "mountain",
  "city",
  "roadtrip",
  "nature",
  "culture",
  "food",
  "festival",
  "wildlife",
  "hiking",
  "skiing",
  "snowboarding",
  "adventure",
  "relaxation",
  "shopping",
  "historical",
  "photography",
  "family",
  "luxury",
  "budget",
  "island",
  "desert",
  "forest",
  "national-park",
  "cruise",
  "sports",
  "wellness",
  "spa",
  "art",
  "music",
  "nightlife",
  "camping",
  "fishing",
  "cycling",
  "diving",
  "surfing",
  "safari",
  "volunteering",
  "business",
  "romantic",
  "honeymoon",
  "local",
  "shopping",
  "architecture",
  "religious",
  "extreme",
  "other",
] as const;
